apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunspot-frontend
  labels:
    name: sunspot-frontend
  # annotations:
  #   "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sunspot-frontend
  template:
    metadata:
      labels:
        app: sunspot-frontend
    spec:
      containers:
        - name: sunspot-frontend
          image: ashishkumar256/trace-ui:1
          imagePullPolicy: Always
          env:
            - name: SUNSPOT_BACKEND_ENDPOINT
              value: "http://sunspot-backend.default.svc.cluster.local:8000"
          ports:
            - name: frontend-port
              containerPort: 5000
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
    name: sunspot-frontend
spec:
    selector:
        app: sunspot-frontend
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
