apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-frontend
  labels:
    name: counter-frontend
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-frontend
  template:
    metadata:
      labels:
        app: counter-frontend
    spec:
      containers:
        - name: counter-frontend
          image: ashishkumar256/trace-ui:4
          imagePullPolicy: Always
          env:
            - name: COUNTER_ENDPOINT
              value: "http://counter-backend.default.svc.cluster.local:8000"
          ports:
            - name: frontend-port
              containerPort: 5000
              protocol: TCP
