apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunspot-backend
  labels:
    name: sunspot-backend
  # annotations:
  #   "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sunspot-backend
  template:
    metadata:
      labels:
        app: sunspot-backend
    spec:
      containers:
        - name: sunspot-backend
          image: ashishkumar256/trace-api:6
          imagePullPolicy: Always
          ports:
            - name: backend-port
              containerPort: 8000
              protocol: TCP
        - name: redis
          image: redis
          imagePullPolicy: Always
          ports:
            - name: redis-port
              containerPort: 6379
              protocol: TCP        
---
apiVersion: v1
kind: Service
metadata:
    name: sunspot-backend
spec:
    selector:
        app: sunspot-backend
    ports:
        - name: backend-port
          protocol: TCP
          port: 8000
          targetPort: 8000
        - name: redis-port
          protocol: TCP
          port: 6379
          targetPort: 6379          